### PR TITLE
Fix Attendance typo (frontend part)

### PR DESCRIPTION
**Pull request by fschindler**

### CODE REVIEW

**Comment by okwast** [comment]
@fschindler is the API part done somewhere else already or is that still to do?

**Comment by fschindler** [comment]
@okwast I guess the API part is described here: https://github.com/edu-hub-project/edu-hub/issues/49

**Review by okwast — APPROVED** [review]
Looking good. Love the increasing of 💃 here.

**Comment by fschindler** [comment]
@okwast thank's for the review and your feedback. Will merge this now.

**Pull request merged**
